name: 'alpine abuild'
author: 'triptixx'
description: 'A Action CI plugin for Alpine Linux package builder'
inputs:
  private_key:
    description: 'the contents of your RSA private key'
  public_key:
    description: 'the contents of your RSA public key'
  packager:
    description: 'the name of the package used in package metadata'
    default: 'Glider Labs <team@gliderlabs.com>'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'package'
  color: 'blue'
